<a href="https://colab.research.google.com/github/sskboonmee/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np #package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

#Numpy Array

## สร้าง Numpy array(matrix)

In [4]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [7]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np_a.shape

(2, 3)

In [9]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

#Matrix transpose

In [10]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

สร้าง Matrix เริ่มต้น (zeros,ones)

In [11]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np_0 = np.ones((5,6))
np_0

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [14]:
np.random.randn(5,5)  #random มาจากเลข normal distribution ที่มี mu = 0 std=1

array([[ 1.10368513, -1.15915896, -0.14314561, -0.42660295,  0.61354918],
       [ 1.07499649, -0.4485255 , -0.9096139 ,  0.57283118,  0.97729653],
       [-0.59546381,  0.82016552, -0.80191335,  0.36228989,  1.2063345 ],
       [-0.60805736,  0.01025485,  0.59263367, -1.56923632, -0.99206155],
       [ 0.05336682,  0.61299466,  1.25396841, -1.4998114 , -0.60249649]])

In [15]:
2+(5*np.random.randn(3,3))

array([[ 0.22368552,  7.31336872, 11.24207587],
       [ 0.14400344, 10.48574299,  1.52717227],
       [ 4.02228464, -0.33965492, -7.07876907]])

In [16]:
np.random.randint(5,11,(4,5))  #random เลขจำนวนเต็ม ระหว่าง (5,11)  ขนาด (4x5)

array([[ 7,  7,  9,  6,  7],
       [ 8,  8,  6,  8,  8],
       [10,  8, 10, 10,  6],
       [ 5,  7,  9,  5,  9]])